version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env.default
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql: