version: '3'

services:
  shortier-mysql:
    image: mysql:5.7
    container_name: shortier-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql

  shortier-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: shortier-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: "production"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - shortier-mysql


volumes:
  mysql: