name: Node.js CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16, 18, 19]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
			- uses: samin/mysql-action@v1
				with:
					mysql version: '5.7'
					mysql database: $MYSQL_DB
					mysql root password: $MYSQL_PASS
					mysql user: $MYSQL_USER
					mysql password: $MYSQL_PASS
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --version
      - run: npm ci --ignore-scripts
      - run: npm test
